oro_menu_config:
    items:
        venue_tab:
            label: Venues
            uri: '#'
            extras:
                icon: icon-building
                position: 2
        shortcut_venue_item:
            label: View Venues
            route: stc_venue_index
        shortcut_venue_create:
            label: Create Venue
            route: stc_venue_create
    tree:
        application_menu:
            children:
                venue_tab:
                    children:
                        shortcut_venue_item: ~
                        shortcut_venue_create: ~