datagrid:
    stc_band_grid:
        source:
            type: orm
            query:
                select:
                    - band.id
                    - band.name
                    - band.description
                    - band.billingAddressStreet
                    - band.billingAddressCity
                    - band.billingAddressState
                    - band.billingAddressPostalcode
                    - band.country
                    - band.phoneOffice
                    - band.website
                    - band.genre
                    - band.actType
                    - band.tickerSymbol
                    - band.tributeto
                    - band.twitter
                    - band.deleted
                    - band.facebook
                    - band.youtube
                    - band.vimeo
                    - band.myspace
                    - band.reverbnation
                    - band.linkdin
                    - band.googleplus
                    - band.jjwgMapsLatC
                    - band.jjwgMapsLngC
                    - band.createdAt
                    - band.updatedAt
                from:
                    - { table: StcBandBundle:Band , alias: band }
                where:
                    and:
                        - band.deleted <> 1
#                join:
#                    left:
#                        - { join: task.status, alias: status }
#                        - { join: task.owner, alias: owner }
#                        - { join: task.assignee, alias: assignee }
#                        - { join: task.relatedContact, alias: relatedContact }
        columns:
            name:
                label: Band Name
            description:
                label: Description
            billingAddressStreet:
                label: Billing Address Street
            billingAddressCity:
                label: Billing Address City
            billingAddressState:
                label: Billing Address State
            billingAddressPostalcode:
                label: Billing Address Zip
            phoneOffice:
                label: Phone
            website:
                label: Website
            genre:
                label: Genre
            actType:
                label: Act Type
            tributeto:
                label: Tribute To
            twitter:
                label: Twitter Page
            facebook:
                label: Facebook Page
            youtube:
                label: Youtube Channel
            vimeo:
                label: Vimeo
            myspace:
                label: MySpace
            googleplus:
                label: Google+ Page
            reverbnation:
                label: Reverb Nation
            linkdin:
                label: LinkdIn
            jjwgMapsLatC:
                label: Location - Lat
            jjwgMapsLngC:
                label: Location - Lng
            createdAt:
                label: stc.band.created_at.label
                frontend_type: datetime
            updatedAt:
                label: stc.band.updated_at.label
                frontend_type: datetime
        properties:
            id: ~
            view_link:
                type: url
                route: stc_band_update
                params: [ id ]
            update_link:
                type: url
                route: stc_band_update
                params: [ id ]
#            delete_link:
#                type: url
#                route: stc_api_delete_band
#                params: [ id ]
        sorters:
            columns:
                name:
                    data_name: band.name
                website:
                    data_name: band.website
                createdAt:
                    data_name: band.createdAt
                updatedAt:
                    data_name: band.updatedAt
                billingAddressStreet:
                    data_name: band.billingAddressStreet
                billingAddressCity:
                    data_name: band.billingAddressCity
                billingAddressState:
                    data_name: band.billingAddressState
                billingAddressPostalcode:
                    data_name: band.billingAddressPostalcode
                phoneOffice:
                    data_name: band.phoneOffice
                genre:
                    data_name: band.genre
                tributeto:
                    data_name: band.tributeto
            default:
                name: DESC
        filters:
            columns:
                name:
                    type: string
                    data_name: band.name
                genre:
                    type: string
                    data_name: band.genre
                billingAddressStreet:
                    type: string
                    data_name: band.billingAddressStreet
                billingAddressCity:
                    type: string
                    data_name: band.billingAddressCity
                billingAddressState:
                    type: string
                    data_name: band.billingAddressState
                billingAddressPostalcode:
                    type: string
                    data_name: band.billingAddressPostalcode
                phoneOffice:
                    type: string
                    data_name: band.phoneOffice
                genre:
                    type: string
                    data_name: band.genre
                tributeto:
                    type: string
                    data_name: band.tributeto
                createdAt:
                    type: datetime
                    data_name: band.createdAt
                updatedAt:
                    type: datetime
                    data_name: band.updatedAt
        actions:
            view:
                type: navigate
                label: View Details
                icon: user
                link: view_link
                rowAction: true
                acl_resource: stc_band_view
            update:
                type: navigate
                label: Update Band
                icon: edit
                link: update_link
                acl_resource: stc_band_update

#            delete:
#                type: delete
#                label: Delete Band
#                link: delete_link
#                icon: trash
#                acl_resource: stc_api_delete_band