stc_performance_bundle:
    resource: "@StcPerformanceBundle/Controller/PerformanceController.php"
    type: annotation
    prefix: /performance

#stc_band_bundle_api:
#    resource: "@StcBandBundle/Controller/Api/Rest/BandController.php"
#    type: rest
#    prefix: api/rest/{version}/acme
#    requirements:
#        version: latest|v1
#    defaults:
#       version: latest